theme: minima
title: Personal Repo
author: Z.G.Su
description: Test for description

# Enable MathJax globally
defaults:
  -
    scope:
      path: "" # This means all files
    values:
      mathjax: true
